spring:
  datasource:
    url: jdbc:sqlite:loan_database.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
      order_inserts: true
      order_updates: true
      jdbc:
        batch_size: 50
        batch_versioned_data: true

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml